dependency:
  name: galaxy
driver:
  name: docker
lint: "ansible-lint ."
platforms:
  - name: ubuntu-2204
    image: golovanovsv/ubuntu:22.04-systemd
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    networks:
      - name: ubuntu-2204
  - name: ubuntu-2004
    image: golovanovsv/ubuntu:20.04-systemd
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    networks:
      - name: ubuntu-2004
  - name: ubuntu-1804
    image: golovanovsv/ubuntu:18.04-systemd
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    networks:
      - name: ubuntu-1804
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: "python3"
verifier:
  name: testinfra
  directory: ../../tests
  # Uncomment for view print() results
  # options:
  #   s: true
